---
title: "stage-2-visualization"
author: "Bekkmo & Guerrero"
date: "2026-04-01"
output: html_document
---

```{r setup}
#| include = FALSE

knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
#| include = FALSE

# Packages
library(tidyverse)
library(rvest)
library(httr)
library(jsonlite)
library(dplyr)
library(tidyr)
library(purrr)
library(stringr)
library(janitor)
library(readr)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)
library(grid)
library(RColorBrewer)
library(scales)

#install.packages("remotes")
#remotes::install_github("hrbrmstr/waffle")
library(waffle)
```

```{r olympics-data}
#Web Scraping

#-----------------------------------
#Summer Olympics
#------------------------------------

#scrape the category page, get all links
url <- "https://en.wikipedia.org/wiki/Category:Summer_Olympics_medal_tables"
page <- read_html(url)

links <- page |>
  html_nodes("#mw-pages a") |>
  html_attr("href") |>
  unique()

links <- links[str_detect(links, "/wiki/\\d{4}_Summer_Olympics_medal_table$")]

links <- paste0("https://en.wikipedia.org", links)

# links

#function to inspect where medal table is
get_medal_table <- function(link) {
  page <- read_html(link)
  year <- str_extract(link, "\\d{4}")
  
  tables <- page %>%
    html_table(fill = TRUE)
  
  medal_table <- NULL
  
  for (tbl in tables) {
    names(tbl) <- names(tbl) %>%
      str_replace_all("\\[.*?\\]", "") %>%
      str_trim() %>%
      make_clean_names()
    
    # check if first column is rank-like
    first_col <- names(tbl)[1]
    
    has_rank <- str_detect(first_col, "rank")
    has_gold <- any(str_detect(names(tbl), "gold"))
    has_silver <- any(str_detect(names(tbl), "silver"))
    has_bronze <- any(str_detect(names(tbl), "bronze"))
    has_total <- any(str_detect(names(tbl), "total"))
    
    if (has_rank & has_gold & has_silver & has_bronze & has_total) {
      medal_table <- tbl
      break
    }
  }
  
  if (is.null(medal_table)) {
    message("No medal table found for: ", link)
    return(NULL)
  }
  
  nation_col <- names(medal_table)[str_detect(names(medal_table), "nation|team|noc")][1]
  gold_col   <- names(medal_table)[str_detect(names(medal_table), "gold")][1]
  silver_col <- names(medal_table)[str_detect(names(medal_table), "silver")][1]
  bronze_col <- names(medal_table)[str_detect(names(medal_table), "bronze")][1]
  total_col  <- names(medal_table)[str_detect(names(medal_table), "total")][1]
  
  medal_table %>%
  transmute(
    country = .data[[nation_col]] %>%
      str_remove_all("\\[.*?\\]") %>%
      str_remove_all("[^A-Za-z ]") %>%
      str_squish(),
    gold = as.numeric(.data[[gold_col]]),
    silver = as.numeric(.data[[silver_col]]),
    bronze = as.numeric(.data[[bronze_col]]),
    total = as.numeric(.data[[total_col]]),
    year = as.numeric(year)
  ) %>%
  filter(!is.na(country)) %>%
  filter(country != "") %>%
  filter(!str_detect(country, "Totals|Total"))
}

#Run funtion in all links
olympics_list <- map(links, get_medal_table)

olympics_list <- olympics_list[!sapply(olympics_list, is.null)]

olympics_raw <- bind_rows(olympics_list)

#Clean data
olympics_clean <- bind_rows(olympics_list) %>%
  mutate(
    country = str_squish(country),
    country = case_when(
      country == "Great Britain" ~ "United Kingdom",
      country == "Mixed team" ~ NA_character_,
      TRUE ~ country
    )
  ) %>%
  filter(!is.na(country), country != "")

#Make sure medal columns are numeric
glimpse(olympics_clean)

#check uniqueness for tidy
olympics_clean %>%
  count(country, year) %>%
  filter(n > 1)

#-----------------------------------
#Winter Olympics
#------------------------------------

# Winter Olympics links
url_winter <- "https://en.wikipedia.org/wiki/Category:Winter_Olympics_medal_tables"
page_winter <- read_html(url_winter)

links_winter <- page_winter |>
  html_nodes("#mw-pages a") |>
  html_attr("href") |>
  unique()

links_winter <- links_winter[str_detect(links_winter, "/wiki/\\d{4}_Winter_Olympics_medal_table$")]

links_winter <- paste0("https://en.wikipedia.org", links_winter)

# Run existing function on winter links
winter_list <- map(links_winter, get_medal_table)

winter_list <- winter_list[!sapply(winter_list, is.null)]

winter_raw <- bind_rows(winter_list)

# Clean winter data
winter_clean <- bind_rows(winter_list) %>%
  mutate(
    country = str_squish(country),
    country = case_when(
      country == "Great Britain" ~ "United Kingdom",
      country == "Mixed team" ~ NA_character_,
      TRUE ~ country
    )
  ) %>%
  filter(!is.na(country), country != "")

# Check uniqueness
winter_clean %>%
  count(country, year) %>%
  filter(n > 1)

#join summer and winter
summer_clean <- olympics_clean %>%
  mutate(season = "Summer")

winter_clean <- winter_clean %>%
  mutate(season = "Winter")

olympics_all <- bind_rows(summer_clean, winter_clean)

#make sure full data set is unique

olympics_all %>%
  count(country, year, season) %>%
  filter(n > 1)
```

```{r world-bank-data}
#-----------------------------------
#World Bank Data
#------------------------------------

# Define API request
get_wb_indicator <- function(indicator, var_name) {
  url <- paste0(
    "https://api.worldbank.org/v2/country/all/indicator/",
    indicator
  )
  params <- list(
    format = "json",
    per_page = 20000
  )
  
  # Make API request
  response <- GET(url = url, query = params)
  
  # Parse JSON
  json <- response |>
    httr::content("text") |>
    fromJSON(flatten = TRUE) # convert from JSON into an R list
  
  # Convert JSON data into a tidy tibble
  df <- as_tibble(json[[2]]) |>
    transmute(
      country = country.value,
      year    = as.numeric(date),
      value   = value
    ) |>
    rename(!!var_name := value) # rename 'value' column to var_name
  
  # Return the cleaned data frame
  return(df)
}

# Create a list of World Bank indicators to download
indicators <- c(
  # GDP/macro
  gross_capital_formation = "NE.GDI.TOTL.ZS",
  gross_savings = "NY.GNS.ICTR.ZS",
  final_consumption = "NE.CON.TOTL.ZS",
  household_consumption = "NE.CON.PRVT.ZS",
  government_consumption = "NE.CON.GOVT.ZS",
  gdp_constant_usd = "NY.GDP.MKTP.KD",
  gdp_ppp = "NY.GDP.MKTP.PP.CD",
  gdp_per_capita_ppp = "NY.GDP.PCAP.PP.CD",

  # inflation/prices
  gdp_deflator = "NY.GDP.DEFL.KD.ZG",
  cpi_all_items = "FP.CPI.TOTL",

  # labor market
  unemployment_total = "SL.UEM.TOTL.ZS",
  unemployment_female = "SL.UEM.TOTL.FE.ZS",
  unemployment_male = "SL.UEM.TOTL.MA.ZS",
  youth_unemployment = "SL.UEM.1524.ZS",
  labor_force_total = "SL.TLF.CACT.ZS",
  labor_force_female = "SL.TLF.CACT.FE.ZS",
  employment_to_population = "SL.EMP.TOTL.SP.ZS",
  vulnerable_employment = "SL.EMP.VULN.ZS",

  # demographics
  population_total = "SP.POP.TOTL",
  population_growth = "SP.POP.GROW",
  urban_population = "SP.URB.TOTL.IN.ZS",
  rural_population = "SP.RUR.TOTL.ZS",
  life_expectancy = "SP.DYN.LE00.IN",
  life_expectancy_female = "SP.DYN.LE00.FE.IN",
  life_expectancy_male = "SP.DYN.LE00.MA.IN",
  fertility_rate = "SP.DYN.TFRT.IN",
  dependency_ratio = "SP.POP.DPND",
  age_dependency_young = "SP.POP.DPND.YG",
  age_dependency_old = "SP.POP.DPND.OL",

  # education
  primary_enrollment = "SE.PRM.ENRR",
  secondary_enrollment = "SE.SEC.ENRR",
  tertiary_enrollment = "SE.TER.ENRR",
  education_spending = "SE.XPD.TOTL.GD.ZS",
  government_education_spending = "SE.XPD.TOTL.GB.ZS",
  literacy_rate = "SE.ADT.LITR.ZS",
  expected_years_schooling = "SE.SCH.LIFE",
  mean_years_schooling = "SE.ADT.1524.LT.ZS",

  # trade
  trade_openness = "NE.TRD.GNFS.ZS",
  exports_goods_services = "NE.EXP.GNFS.ZS",
  imports_goods_services = "NE.IMP.GNFS.ZS",
  fdi_inflow = "BX.KLT.DINV.CD.WD",
  fdi_outflow = "BM.KLT.DINV.CD.WD",
  portfolio_inflow = "BX.PEF.TOTL.CD.WD",

  # finance
  private_credit = "FS.AST.PRVT.GD.ZS",
  broad_money = "FM.LBL.BMNY.GD.ZS",
  money_growth = "FM.LBL.BMNY.ZG",
  lending_rate = "FR.INR.LEND",
  deposit_rate = "FR.INR.DPST",
  real_interest_rate = "FR.INR.RINR",

  # government
  tax_revenue = "GC.TAX.TOTL.GD.ZS",
  government_expenditure = "GC.XPN.TOTL.GD.ZS",
  government_revenue = "GC.REV.XGRT.GD.ZS",
  public_debt = "GC.DOD.TOTL.GD.ZS",
  
  # inequality/poverty
  gini = "SI.POV.GINI",
  poverty_2usd = "SI.POV.DDAY",
  poverty_3_2usd = "SI.POV.UMIC",
  income_share_top10 = "SI.DST.10TH.10",
  poverty_national = "SI.POV.NAHC",

  # governance
  rule_of_law = "RL.EST",
  control_corruption = "CC.EST",
  gov_effectiveness = "GE.EST",
  regulatory_quality = "RQ.EST",
  political_stability = "PV.EST",
  voice_accountability = "VA.EST",

  # environment
  renewable_energy = "EG.FEC.RNEW.ZS",
  energy_use = "EG.USE.PCAP.KG.OE",
  electricity_access = "EG.ELC.ACCS.ZS",
  forest_area = "AG.LND.FRST.ZS",

  # health
  life_expectancy = "SP.DYN.LE00.IN",
  infant_mortality = "SP.DYN.IMRT.IN",
  child_mortality = "SH.DYN.MORT",
  health_expenditure = "SH.XPD.CHEX.GD.ZS",
  physicians = "SH.MED.PHYS.ZS",
  hospital_beds = "SH.MED.BEDS.ZS",
  immunization_dpt = "SH.IMM.IDPT",
  immunization_measles = "SH.IMM.MEAS"
)

# Download indicators into a list of data frames
indicators_list <- imap(indicators, get_wb_indicator)

# Combine indicators data sets into one wide dataset
# reduce() combined two elements of a list at a time until one object is left
indicators_final <- reduce(indicators_list, left_join, by = c("country", "year"))

olympics_indicators <- left_join(olympics_all, indicators_final, by = c("country", "year"))
```

```{r data-cleaning}
#----------------------------
# Cleaning Data Set
#---------------------------

#Selecting data range from most complete years

# Count non-missing indicators per year
year_completeness <- olympics_indicators %>%
  group_by(year) %>%
  summarise(
    non_missing = sum(!is.na(across(where(is.numeric)))),
    total_values = n() * ncol(select(., where(is.numeric))),
    completeness_ratio = non_missing / total_values
  ) %>%
  arrange(year)

#Find where completeness increases a lot
year_completeness <- year_completeness %>%
  mutate(change = completeness_ratio - lag(completeness_ratio))

start_year <- year_completeness %>%
  filter(change == max(change, na.rm = TRUE)) %>%
  pull(year)

#filter data set to most complete years
olympics_final <- olympics_indicators %>%
  filter(year >= start_year)

#Check how many years were kept
summary(olympics_final$year)
```

```{r visualization1}
#-----------------------------------------
# Data set improved for visualization
#-----------------------------------------

#Check raw data plots

#Medals Distribution
ggplot(olympics_final, aes(x = total)) +
  geom_histogram(bins = 30) +
  labs(
    title = "Raw Distribution of Olympic Medals",
    x = "Total Medals",
    y = "Number of Country-Year Observations"
  ) +
  theme_minimal()

#GDP per capital
ggplot(olympics_final, aes(x = gdp_per_capita_ppp)) +
  geom_histogram(bins = 30) +
  labs(
    title = "Raw Distribution of GDP per Capita",
    x = "GDP per Capita (PPP)",
    y = "Number of Country-Year Observations"
  ) +
  theme_minimal()

#population
ggplot(olympics_final, aes(x = population_total)) +
  geom_histogram(bins = 30) +
  labs(
    title = "Raw Distribution of Population",
    x = "Population",
    y = "Number of Country-Year Observations"
  ) +
  theme_minimal()

#--------------------------
#Data log Transformation
#--------------------------
#Normalizing to improve is right skewed - Log transformation
olympics_viz <- olympics_final %>%
  mutate(
    medals_per_million = total / (population_total / 1e6),
    log_gdp = log(gdp_per_capita_ppp),
    log_population = log(population_total)
  )

#removing NAs since log can't have zeros
olympics_viz_clean <- olympics_viz %>%
  filter(
    !is.na(log_population),
    !is.na(medals_per_million),
    is.finite(log_population),
    is.finite(medals_per_million)
  )

#Plots after transformation
#Medals Distribution 
ggplot(olympics_viz_clean, aes(x = medals_per_million)) +
  geom_histogram(bins = 30, fill = "steelblue", color = "white") +
  coord_cartesian(xlim = c(0, 10)) +
  labs(
    title = "Distribution of Medals per Million People (Zoomed In)",
    x = "Medals per Million",
    y = "Number of Country-Year Observations"
  ) +
  theme_minimal()

#GDP per capital
ggplot(olympics_viz_clean, aes(x = log_gdp)) +
  geom_histogram(bins = 30, fill = "steelblue", color = "white") +
  labs(
    title = "Log-Transformed GDP per Capita Distribution",
    x = "Log GDP per Capita",
    y = "Number of Country-Year Observations"
  ) +
  theme_minimal()

#Population
ggplot(olympics_viz_clean, aes(x = log_population)) +
  geom_histogram(bins = 30, fill = "steelblue", color = "white") +
  labs(
    title = "Log-Transformed Population Distribution",
    x = "Log Population",
    y = "Number of Country-Year Observations"
  ) +
  theme_minimal()

#Understand relationships between variables

#relationship between GDP and Medals
ggplot(olympics_viz_clean, aes(x = log_gdp, y = medals_per_million)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Relationship Between GDP per Capita and Olympic Success",
    x = "Log GDP per Capita",
    y = "Medals per Million"
  ) +
  theme_minimal()

#relationship 
ggplot(olympics_viz_clean, aes(x = log_population, y = medals_per_million)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Relationship Between Population and Olympic Success",
    x = "Log Population",
    y = "Medals per Million"
  ) +
  theme_minimal()

# GDP vs medals per million (binned median trend)
ggplot(olympics_viz_clean, aes(x = log_gdp, y = medals_per_million)) +
  geom_point(alpha = 0.12) +
  geom_smooth(se = FALSE, linewidth = 1.2, color = "steelblue")+
  coord_cartesian(ylim = c(0, 5)) +
  labs(
    title = "Relationship Between GDP per Capita and Medals per Million",
    x = "Log GDP per Capita",
    y = "Medals per Million"
  ) +
  theme_minimal()

#Total medals over time for a topmajor countries
top_countries_total <- olympics_final %>%
  group_by(country) %>%
  summarise(total_medals_all_years = sum(total, na.rm = TRUE)) %>%
  slice_max(total_medals_all_years, n = 10)

ggplot(top_countries_total,
       aes(x = reorder(country, total_medals_all_years),
           y = total_medals_all_years)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Top 10 Countries by Total Olympic Medals",
    x = NULL,
    y = "Total Medals"
  ) +
  theme_minimal()
```

```{r visualization2}
#Choropleth world map with a sequential color scale

# -----------------------------------
# Get world map data
# -----------------------------------

world <- ne_countries(scale = "medium", returnclass = "sf")

# -----------------------------------
# Aggregate Olympic medals by country and Fix country names to improve matching
# -----------------------------------

medals_map_clean <- olympics_final %>%
  group_by(country, season) %>%
  summarise(total_medals = sum(total, na.rm = TRUE), .groups = "drop") %>%
  mutate(
    country = case_when(
      country == "United States" ~ "United States of America",
      country == "Russia" ~ "Russian Federation",
      #country == "South Korea" ~ "Republic of Korea",
      country == "Republic of Korea" ~ "South Korea",
      #country == "North Korea" ~ "Dem. Rep. Korea",
      country == "Dem. Rep. Korea" ~ "North Korea",
      #country == "Iran" ~ "Iran",
      #country == "Venezuela" ~ "Venezuela",
      country == "Czech Republic" ~ "Czechia",
      #country == "Slovakia" ~ "Slovakia",
      #country == "Moldova" ~ "Moldova",
      #country == "Syria" ~ "Syria",
      #country == "Bolivia" ~ "Bolivia",
      #country == "Tanzania" ~ "Tanzania",
      #country == "Laos" ~ "Laos",
      #country == "Vietnam" ~ "Vietnam",
      #country == "Brunei" ~ "Brunei",
      country == "Cape Verde" ~ "Cabo Verde",
      country == "Ivory Coast" ~ "Côte d'Ivoire",
      country == "Macedonia" ~ "North Macedonia",
      country == "Chinese Taipei" ~ "Taiwan",
      #Adding medals to Russia when competed with different team names
      country %in% c("Russian Federation", "ROC", "Olympic Athletes from Russia") ~ "Russia",
      TRUE ~ country
    )
  ) %>%
  filter(!country %in% c(
    "Czechoslovakia",
    "FR Yugoslavia",
    "Independent Olympic Athletes",
    "Independent Olympic Participants",
    "Individual Neutral Athletes",
    "Refugee Olympic Team",
    "Serbia and Montenegro",
    "Unified Team"
  ))

# -----------------------------------
# Ensure all countries exist for both seasons
# -----------------------------------

medals_map_complete <- medals_map_clean %>%
  tidyr::complete(
    country = unique(world$name),
    season = c("Summer", "Winter")
  )

# -----------------------------------
# Join map with medal data
# -----------------------------------

world_medals <- world %>%
  left_join(medals_map_complete, by = c("name" = "country"))

# -----------------------------------
# Plot
# -----------------------------------

ggplot(world_medals) +
  geom_sf(aes(fill = total_medals), color = "white", linewidth = 0.2) +
  scale_fill_distiller(
  palette = "YlGnBu",
  direction = 1,
  trans = "sqrt",
  na.value = "gray90",
  name = "Total medals",
  breaks = seq(200, 1200, by = 200)
) +
  guides(
    fill = guide_colorbar(
      direction = "horizontal",
      title.position = "left",
      title.hjust = 0.5,
      barwidth = unit(12, "cm"),
      barheight = unit(0.7, "cm")
    )
  ) +
  labs(
    title = "Olympic Medal Totals Across Participating Countries",
    subtitle = "Data covers Olympic Games from 1996 to 2024 \nCountries in gray do not appear in the dataset",
    caption = "Lighter colors indicate lower total medal counts"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
    plot.subtitle = element_text(hjust = 0.5),
    plot.caption = element_text(hjust = 0.5),
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(face = "bold", size = 12),
    legend.text = element_text(size = 10)
  ) +
  facet_wrap(~season)
```

```{r visualization3}
model <- lm(medals_per_million ~ log_gdp, data = olympics_viz_clean)

olympics_model <- olympics_viz_clean %>%
  mutate(
    expected = predict(model, newdata = olympics_viz_clean),
    residual = medals_per_million - expected
  )

top_overperformers <- olympics_model %>%
  group_by(country) %>%
  summarise(avg_residual = mean(residual, na.rm = TRUE)) %>%
  slice_max(avg_residual, n = 10)

ggplot(top_overperformers,
       aes(x = reorder(country, avg_residual), y = avg_residual)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Countries That Overperform in Olympic Success",
    subtitle = "Relative to GDP per capita expectations",
    x = NULL,
    y = "Average Overperformance (Residual)"
  ) +
  theme_minimal()
```

```{r visualization4}
olympics_viz_clean |>
  select(country, medals_per_million) |>
  arrange(desc(medals_per_million)) |>
  
  ggplot(aes(x = total, y = log_gdp)) +
  geom_rug(color = "steelblue") +
  geom_point(color = "steelblue", alpha = 0.6) +
  labs(
    title = "Distribution of Log GDP per Capita by Olympic Success Level",
    x = "Total Medals",
    y = "Log GDP per Capita"
  ) +
  theme_minimal() +
  facet_wrap(~season)
```

```{r visualization5}
medals_long <- olympics_viz_clean %>%
  select(country, year, log_gdp, gold, silver, bronze) %>%
  pivot_longer(
    cols = c(gold, silver, bronze),
    names_to = "medal_type",
    values_to = "medals"
  )

ggplot(medals_long, aes(x = log_gdp, y = medals, color = medal_type)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "loess", se = FALSE, linewidth = 1.5) +
  facet_wrap(~ medal_type) +
  scale_color_manual(
    values = c(
      gold = "#D4AF37",
      silver = "#C0C0C0",
      bronze = "#CD7F32"
    )
  ) +
  guides(color = "none") +
  labs(
    title = "GDP per Capita and Olympic Medal Types",
    x = "Log GDP per Capita",
    y = "Medals",
    color = ""
  ) +
  theme_minimal()
```

```{r visualization6}
country_medals <- olympics_final %>%
  group_by(country) %>%
  summarise(
    gold = sum(gold, na.rm = TRUE),
    silver = sum(silver, na.rm = TRUE),
    bronze = sum(bronze, na.rm = TRUE),
    total = sum(total, na.rm = TRUE),
    .groups = "drop"
  )

norway <- country_medals %>%
  filter(country == "Norway") %>%
  select(gold, silver, bronze)

waffle(
  c(
    Gold = norway$gold,
    Silver = norway$silver,
    Bronze = norway$bronze
  ),
  rows = 10,
  colors = c("#D4AF37", "#C0C0C0", "#CD7F32"),
  title = "Norway Olympic Medals",
  xlab = "1 square = 1 medal"
)

top10 <- country_medals %>%
  slice_max(total, n = 10)

medals_long_counts <- top10 %>%
  pivot_longer(
    cols = c(gold, silver, bronze),
    names_to = "medal",
    values_to = "count"
  )

ggplot(medals_long_counts, aes(fill = medal, values = count)) +
  geom_waffle(
    n_rows = 10,
    color = "white",
    size = 0.25
  ) +
  facet_wrap(~ country, ncol = 2) +
  scale_fill_manual(
    values = c(
      gold = "#D4AF37",
      silver = "#C0C0C0",
      bronze = "#CD7F32"
    )
  ) +
  theme_minimal() +
  labs(title = "Olympic Medal Composition by Country",
       caption = "For Top 10 Countries in Total Medal Count")
```
